# This is a configuration file for the bacon tool
# More info at https://github.com/Canop/bacon

default_job = "clippy"

[jobs]

[jobs.clippy]
command = ["cargo", "clippy", "--all-targets", "--color", "always"]
need_stdout = false
watch = ["build.rs", "tests", "benches", "examples"]
on_success = "job:test"

[jobs.test]
command = ["cargo", "nextest", "run", "--color", "always"]
need_stdout = true
watch = ["build.rs", "tests"]
