[package]
name = "interpreter"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
maplit = "1"
syn = { version = "1", default-features = false, features = ["parsing", "full", "extra-traits"] }
