[package]
name = "interpreter-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
pretty_env_logger = "0.4"
structopt = "0.3"
anyhow = "1"
log = "0.4"
rustyline = "9"
syn = { version = "1", default-features = false, features = ["parsing", "full", "extra-traits"] }
interpreter = { path = ".." }
